DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS travels;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE travels (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  destination TEXT NOT NULL,
  traveldate DATE NOT NULL,
  returndate DATE,
  day_trip BOOLEAN NOT NULL,
  body TEXT NOT NULL,
  will_drive BOOLEAN,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
